### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by NestorEduardo** [Giampierospec/itlaBike#3]
- [x] Un usuario puede registrarse o iniciar sesión con Facebook para publicar algún anuncio de su interés.
- [x] Un usuario puede registrarse o iniciar sesión de manera tradicional.
- [x] No se puede permitir crear dos usuarios con el mismo correo.
- [x] El usuario puede cerrar sesión.
- [x] Debe haber una interfaz para que el usuario pueda manejar sus anuncios.

**Comment by NestorEduardo** [comment]
Hecha la opción de registrarse e iniciar sesión con Facebook.

**Comment by Giampierospec** [comment]
Ya el usuario se puede desloggear.
Lo de que no se pueda loggear con el mismo email ya lo hice.

**Comment by Giampierospec** [comment]
El usuario puede ver sus anuncios que el ha publicado

**Comment by Giampierospec** [comment]
el usuario puede editar y/o eliminar la info de sus anuncios
