### ISSUE TITLE
Detalles de un anuncio

### ISSUE THREAD

**Issue by NestorEduardo** [Giampierospec/itlaBike#5]
- [x] Al visualizar un anuncio se deberá mostrar sus datos
- [x] Una opción de comentarios (pueden ser de Facebook) 
- [x] La página se puede compartir mediante el botón Share de Facebook.
- [x] Por cada anuncio se puede subir hasta cinco fotos.

Este issue depende del issue #1

**Comment by Giampierospec** [comment]
Se puede compartir

**Comment by Giampierospec** [comment]
Ya los comentarios están listos.!
