### ISSUE TITLE
Integracion con Facebook, Boton "Compartir"

### ISSUE THREAD

**Issue by Maxi-Heartnet** [Giampierospec/itlaBike#8]
Crear botón compartir en Facebook para cada publicación que se haga.

**Comment by Maxi-Heartnet** [comment]
A mi percepción, El código esta terminado, hay que subirlo a un host para ver si funciona debidamente

**Comment by Giampierospec** [comment]
Funciona el hosting esta en la descripcion del github. solo hay que habilitarlo para mas usuarios
